/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    LSP8Loogies: {
      address: "0x4C4a2f8c81640e47606d3fd77B353E87Ba015584",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "contractOwner",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          inputs: [],
          name: "ERC725Y_DataKeysValuesEmptyArray",
          type: "error",
        },
        {
          inputs: [],
          name: "ERC725Y_DataKeysValuesLengthMismatch",
          type: "error",
        },
        {
          inputs: [],
          name: "ERC725Y_MsgValueDisallowed",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "bytes",
              name: "storedData",
              type: "bytes",
            },
          ],
          name: "InvalidExtensionAddress",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "bytes",
              name: "data",
              type: "bytes",
            },
          ],
          name: "InvalidFunctionSelector",
          type: "error",
        },
        {
          inputs: [],
          name: "LSP4TokenNameNotEditable",
          type: "error",
        },
        {
          inputs: [],
          name: "LSP4TokenSymbolNotEditable",
          type: "error",
        },
        {
          inputs: [],
          name: "LSP4TokenTypeNotEditable",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "callIndex",
              type: "uint256",
            },
          ],
          name: "LSP8BatchCallFailed",
          type: "error",
        },
        {
          inputs: [],
          name: "LSP8CannotSendToAddressZero",
          type: "error",
        },
        {
          inputs: [],
          name: "LSP8CannotUseAddressZeroAsOperator",
          type: "error",
        },
        {
          inputs: [],
          name: "LSP8InvalidTransferBatch",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "tokenId",
              type: "bytes32",
            },
          ],
          name: "LSP8NonExistentTokenId",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "operator",
              type: "address",
            },
            {
              internalType: "bytes32",
              name: "tokenId",
              type: "bytes32",
            },
          ],
          name: "LSP8NonExistingOperator",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "tokenId",
              type: "bytes32",
            },
            {
              internalType: "address",
              name: "caller",
              type: "address",
            },
          ],
          name: "LSP8NotTokenOperator",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "tokenOwner",
              type: "address",
            },
            {
              internalType: "bytes32",
              name: "tokenId",
              type: "bytes32",
            },
            {
              internalType: "address",
              name: "caller",
              type: "address",
            },
          ],
          name: "LSP8NotTokenOwner",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "tokenReceiver",
              type: "address",
            },
          ],
          name: "LSP8NotifyTokenReceiverContractMissingLSP1Interface",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "tokenReceiver",
              type: "address",
            },
          ],
          name: "LSP8NotifyTokenReceiverIsEOA",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "operator",
              type: "address",
            },
            {
              internalType: "bytes32",
              name: "tokenId",
              type: "bytes32",
            },
          ],
          name: "LSP8OperatorAlreadyAuthorized",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "caller",
              type: "address",
            },
            {
              internalType: "address",
              name: "tokenOwner",
              type: "address",
            },
            {
              internalType: "bytes32",
              name: "tokenId",
              type: "bytes32",
            },
          ],
          name: "LSP8RevokeOperatorNotAuthorized",
          type: "error",
        },
        {
          inputs: [],
          name: "LSP8TokenContractCannotHoldValue",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "tokenId",
              type: "bytes32",
            },
          ],
          name: "LSP8TokenIdAlreadyMinted",
          type: "error",
        },
        {
          inputs: [],
          name: "LSP8TokenIdFormatNotEditable",
          type: "error",
        },
        {
          inputs: [],
          name: "LSP8TokenIdsDataEmptyArray",
          type: "error",
        },
        {
          inputs: [],
          name: "LSP8TokenIdsDataLengthMismatch",
          type: "error",
        },
        {
          inputs: [],
          name: "LSP8TokenOwnerCannotBeOperator",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "tokenId",
              type: "bytes32",
            },
            {
              internalType: "address",
              name: "oldOwner",
              type: "address",
            },
            {
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "LSP8TokenOwnerChanged",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "bytes4",
              name: "functionSelector",
              type: "bytes4",
            },
          ],
          name: "NoExtensionFoundForFunctionSelector",
          type: "error",
        },
        {
          inputs: [],
          name: "OwnableCannotSetZeroAddressAsOwner",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "dataKey",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "bytes",
              name: "dataValue",
              type: "bytes",
            },
          ],
          name: "DataChanged",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "operator",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "tokenOwner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "bytes32",
              name: "tokenId",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "bytes",
              name: "operatorNotificationData",
              type: "bytes",
            },
          ],
          name: "OperatorAuthorizationChanged",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "operator",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "tokenOwner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "bytes32",
              name: "tokenId",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "notified",
              type: "bool",
            },
            {
              indexed: false,
              internalType: "bytes",
              name: "operatorNotificationData",
              type: "bytes",
            },
          ],
          name: "OperatorRevoked",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "previousOwner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "OwnershipTransferred",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "tokenId",
              type: "bytes32",
            },
            {
              indexed: true,
              internalType: "bytes32",
              name: "dataKey",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "bytes",
              name: "dataValue",
              type: "bytes",
            },
          ],
          name: "TokenIdDataChanged",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "address",
              name: "operator",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              indexed: true,
              internalType: "bytes32",
              name: "tokenId",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "force",
              type: "bool",
            },
            {
              indexed: false,
              internalType: "bytes",
              name: "data",
              type: "bytes",
            },
          ],
          name: "Transfer",
          type: "event",
        },
        {
          stateMutability: "payable",
          type: "fallback",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "operator",
              type: "address",
            },
            {
              internalType: "bytes32",
              name: "tokenId",
              type: "bytes32",
            },
            {
              internalType: "bytes",
              name: "operatorNotificationData",
              type: "bytes",
            },
          ],
          name: "authorizeOperator",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "tokenOwner",
              type: "address",
            },
          ],
          name: "balanceOf",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes[]",
              name: "data",
              type: "bytes[]",
            },
          ],
          name: "batchCalls",
          outputs: [
            {
              internalType: "bytes[]",
              name: "results",
              type: "bytes[]",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "count",
              type: "uint256",
            },
          ],
          name: "batchMintItems",
          outputs: [
            {
              internalType: "bytes32[]",
              name: "",
              type: "bytes32[]",
            },
          ],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256[]",
              name: "ids",
              type: "uint256[]",
            },
          ],
          name: "batchTokenExists",
          outputs: [
            {
              internalType: "bool[]",
              name: "",
              type: "bool[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          name: "chubbiness",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          name: "color",
          outputs: [
            {
              internalType: "bytes3",
              name: "",
              type: "bytes3",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "curve",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "getAllTokenIds",
          outputs: [
            {
              internalType: "uint256[]",
              name: "",
              type: "uint256[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "key",
              type: "bytes32",
            },
          ],
          name: "getData",
          outputs: [
            {
              internalType: "bytes",
              name: "",
              type: "bytes",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32[]",
              name: "keys",
              type: "bytes32[]",
            },
          ],
          name: "getDataBatch",
          outputs: [
            {
              internalType: "bytes[]",
              name: "",
              type: "bytes[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32[]",
              name: "tokenIds",
              type: "bytes32[]",
            },
            {
              internalType: "bytes32[]",
              name: "dataKeys",
              type: "bytes32[]",
            },
          ],
          name: "getDataBatchForTokenIds",
          outputs: [
            {
              internalType: "bytes[]",
              name: "dataValues",
              type: "bytes[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "tokenId",
              type: "bytes32",
            },
            {
              internalType: "bytes32",
              name: "dataKey",
              type: "bytes32",
            },
          ],
          name: "getDataForTokenId",
          outputs: [
            {
              internalType: "bytes",
              name: "dataValue",
              type: "bytes",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "tokenId",
              type: "bytes32",
            },
          ],
          name: "getOperatorsOf",
          outputs: [
            {
              internalType: "address[]",
              name: "",
              type: "address[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "offset",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "pageSize",
              type: "uint256",
            },
          ],
          name: "getTokenIdsPaginated",
          outputs: [
            {
              internalType: "uint256[]",
              name: "",
              type: "uint256[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "upAddress",
              type: "address",
            },
          ],
          name: "getUPName",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256[]",
              name: "tokenIds",
              type: "uint256[]",
            },
            {
              internalType: "address[]",
              name: "owners",
              type: "address[]",
            },
            {
              internalType: "bytes3[]",
              name: "tokenColors",
              type: "bytes3[]",
            },
            {
              internalType: "uint256[]",
              name: "tokenChubbiness",
              type: "uint256[]",
            },
            {
              internalType: "uint256[]",
              name: "tokenMouthLength",
              type: "uint256[]",
            },
            {
              internalType: "string[]",
              name: "tokenUsernames",
              type: "string[]",
            },
          ],
          name: "importLegacyTokens",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256[]",
              name: "tokenIds",
              type: "uint256[]",
            },
            {
              internalType: "address[]",
              name: "owners",
              type: "address[]",
            },
          ],
          name: "importLegacyTokensSimple",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "operator",
              type: "address",
            },
            {
              internalType: "bytes32",
              name: "tokenId",
              type: "bytes32",
            },
          ],
          name: "isOperatorFor",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "account",
              type: "address",
            },
          ],
          name: "isUniversalProfile",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "limit",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "mintItem",
          outputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
          ],
          name: "mintLoogie",
          outputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          name: "mouthLength",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "name",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "price",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "recipient",
          outputs: [
            {
              internalType: "address payable",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "tokenId",
              type: "bytes32",
            },
          ],
          name: "renderTokenById",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "renounceOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "operator",
              type: "address",
            },
            {
              internalType: "bytes32",
              name: "tokenId",
              type: "bytes32",
            },
            {
              internalType: "bool",
              name: "notify",
              type: "bool",
            },
            {
              internalType: "bytes",
              name: "operatorNotificationData",
              type: "bytes",
            },
          ],
          name: "revokeOperator",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "key",
              type: "bytes32",
            },
            {
              internalType: "bytes",
              name: "value",
              type: "bytes",
            },
          ],
          name: "setData",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32[]",
              name: "keys",
              type: "bytes32[]",
            },
            {
              internalType: "bytes[]",
              name: "values",
              type: "bytes[]",
            },
          ],
          name: "setDataBatch",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32[]",
              name: "tokenIds",
              type: "bytes32[]",
            },
            {
              internalType: "bytes32[]",
              name: "dataKeys",
              type: "bytes32[]",
            },
            {
              internalType: "bytes[]",
              name: "dataValues",
              type: "bytes[]",
            },
          ],
          name: "setDataBatchForTokenIds",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "tokenId",
              type: "bytes32",
            },
            {
              internalType: "bytes32",
              name: "dataKey",
              type: "bytes32",
            },
            {
              internalType: "bytes",
              name: "dataValue",
              type: "bytes",
            },
          ],
          name: "setDataForTokenId",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "tokenId",
              type: "bytes32",
            },
            {
              internalType: "string",
              name: "username",
              type: "string",
            },
          ],
          name: "setUPUsername",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "account",
              type: "address",
            },
            {
              internalType: "bytes4",
              name: "interfaceId",
              type: "bytes4",
            },
          ],
          name: "supportsERC165InterfaceUnchecked",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes4",
              name: "interfaceId",
              type: "bytes4",
            },
          ],
          name: "supportsInterface",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "symbol",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
          ],
          name: "tokenExists",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "tokenOwner",
              type: "address",
            },
          ],
          name: "tokenIdsOf",
          outputs: [
            {
              internalType: "bytes32[]",
              name: "",
              type: "bytes32[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "tokenId",
              type: "bytes32",
            },
          ],
          name: "tokenOwnerOf",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "tokenId",
              type: "bytes32",
            },
          ],
          name: "tokenURI",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "totalSupply",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              internalType: "bytes32",
              name: "tokenId",
              type: "bytes32",
            },
            {
              internalType: "bool",
              name: "force",
              type: "bool",
            },
            {
              internalType: "bytes",
              name: "data",
              type: "bytes",
            },
          ],
          name: "transfer",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address[]",
              name: "from",
              type: "address[]",
            },
            {
              internalType: "address[]",
              name: "to",
              type: "address[]",
            },
            {
              internalType: "bytes32[]",
              name: "tokenId",
              type: "bytes32[]",
            },
            {
              internalType: "bool[]",
              name: "force",
              type: "bool[]",
            },
            {
              internalType: "bytes[]",
              name: "data",
              type: "bytes[]",
            },
          ],
          name: "transferBatch",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "transferOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          name: "upUsernames",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          stateMutability: "payable",
          type: "receive",
        },
      ],
      inheritedFunctions: {},
    },
    YourCollectible: {
      address: "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0",
      abi: [
        {
          inputs: [],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "owner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "approved",
              type: "address",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
          ],
          name: "Approval",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "owner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "operator",
              type: "address",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "approved",
              type: "bool",
            },
          ],
          name: "ApprovalForAll",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "previousOwner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "OwnershipTransferred",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
          ],
          name: "Transfer",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
          ],
          name: "approve",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "owner",
              type: "address",
            },
          ],
          name: "balanceOf",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "chubbiness",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "color",
          outputs: [
            {
              internalType: "bytes3",
              name: "",
              type: "bytes3",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "curve",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
          ],
          name: "getApproved",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "owner",
              type: "address",
            },
            {
              internalType: "address",
              name: "operator",
              type: "address",
            },
          ],
          name: "isApprovedForAll",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "limit",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "mintItem",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "mouthLength",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "name",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
          ],
          name: "ownerOf",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "price",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "recipient",
          outputs: [
            {
              internalType: "address payable",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
          ],
          name: "renderTokenById",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "renounceOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
          ],
          name: "safeTransferFrom",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
            {
              internalType: "bytes",
              name: "data",
              type: "bytes",
            },
          ],
          name: "safeTransferFrom",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "operator",
              type: "address",
            },
            {
              internalType: "bool",
              name: "approved",
              type: "bool",
            },
          ],
          name: "setApprovalForAll",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes4",
              name: "interfaceId",
              type: "bytes4",
            },
          ],
          name: "supportsInterface",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "symbol",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "index",
              type: "uint256",
            },
          ],
          name: "tokenByIndex",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "owner",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "index",
              type: "uint256",
            },
          ],
          name: "tokenOfOwnerByIndex",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
          ],
          name: "tokenURI",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "totalSupply",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "tokenId",
              type: "uint256",
            },
          ],
          name: "transferFrom",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "transferOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
    YourLSP8Collectible: {
      address: "0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9",
      abi: [
        {
          inputs: [
            {
              internalType: "string",
              name: "name",
              type: "string",
            },
            {
              internalType: "string",
              name: "symbol",
              type: "string",
            },
            {
              internalType: "address",
              name: "contractOwner",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          inputs: [],
          name: "ERC725Y_DataKeysValuesEmptyArray",
          type: "error",
        },
        {
          inputs: [],
          name: "ERC725Y_DataKeysValuesLengthMismatch",
          type: "error",
        },
        {
          inputs: [],
          name: "ERC725Y_MsgValueDisallowed",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "bytes",
              name: "storedData",
              type: "bytes",
            },
          ],
          name: "InvalidExtensionAddress",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "bytes",
              name: "data",
              type: "bytes",
            },
          ],
          name: "InvalidFunctionSelector",
          type: "error",
        },
        {
          inputs: [],
          name: "LSP4TokenNameNotEditable",
          type: "error",
        },
        {
          inputs: [],
          name: "LSP4TokenSymbolNotEditable",
          type: "error",
        },
        {
          inputs: [],
          name: "LSP4TokenTypeNotEditable",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "callIndex",
              type: "uint256",
            },
          ],
          name: "LSP8BatchCallFailed",
          type: "error",
        },
        {
          inputs: [],
          name: "LSP8CannotSendToAddressZero",
          type: "error",
        },
        {
          inputs: [],
          name: "LSP8CannotUseAddressZeroAsOperator",
          type: "error",
        },
        {
          inputs: [],
          name: "LSP8InvalidTransferBatch",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "tokenId",
              type: "bytes32",
            },
          ],
          name: "LSP8NonExistentTokenId",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "operator",
              type: "address",
            },
            {
              internalType: "bytes32",
              name: "tokenId",
              type: "bytes32",
            },
          ],
          name: "LSP8NonExistingOperator",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "tokenId",
              type: "bytes32",
            },
            {
              internalType: "address",
              name: "caller",
              type: "address",
            },
          ],
          name: "LSP8NotTokenOperator",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "tokenOwner",
              type: "address",
            },
            {
              internalType: "bytes32",
              name: "tokenId",
              type: "bytes32",
            },
            {
              internalType: "address",
              name: "caller",
              type: "address",
            },
          ],
          name: "LSP8NotTokenOwner",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "tokenReceiver",
              type: "address",
            },
          ],
          name: "LSP8NotifyTokenReceiverContractMissingLSP1Interface",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "tokenReceiver",
              type: "address",
            },
          ],
          name: "LSP8NotifyTokenReceiverIsEOA",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "operator",
              type: "address",
            },
            {
              internalType: "bytes32",
              name: "tokenId",
              type: "bytes32",
            },
          ],
          name: "LSP8OperatorAlreadyAuthorized",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "caller",
              type: "address",
            },
            {
              internalType: "address",
              name: "tokenOwner",
              type: "address",
            },
            {
              internalType: "bytes32",
              name: "tokenId",
              type: "bytes32",
            },
          ],
          name: "LSP8RevokeOperatorNotAuthorized",
          type: "error",
        },
        {
          inputs: [],
          name: "LSP8TokenContractCannotHoldValue",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "tokenId",
              type: "bytes32",
            },
          ],
          name: "LSP8TokenIdAlreadyMinted",
          type: "error",
        },
        {
          inputs: [],
          name: "LSP8TokenIdFormatNotEditable",
          type: "error",
        },
        {
          inputs: [],
          name: "LSP8TokenIdsDataEmptyArray",
          type: "error",
        },
        {
          inputs: [],
          name: "LSP8TokenIdsDataLengthMismatch",
          type: "error",
        },
        {
          inputs: [],
          name: "LSP8TokenOwnerCannotBeOperator",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "tokenId",
              type: "bytes32",
            },
            {
              internalType: "address",
              name: "oldOwner",
              type: "address",
            },
            {
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "LSP8TokenOwnerChanged",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "bytes4",
              name: "functionSelector",
              type: "bytes4",
            },
          ],
          name: "NoExtensionFoundForFunctionSelector",
          type: "error",
        },
        {
          inputs: [],
          name: "OwnableCannotSetZeroAddressAsOwner",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "dataKey",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "bytes",
              name: "dataValue",
              type: "bytes",
            },
          ],
          name: "DataChanged",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "operator",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "tokenOwner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "bytes32",
              name: "tokenId",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "bytes",
              name: "operatorNotificationData",
              type: "bytes",
            },
          ],
          name: "OperatorAuthorizationChanged",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "operator",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "tokenOwner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "bytes32",
              name: "tokenId",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "notified",
              type: "bool",
            },
            {
              indexed: false,
              internalType: "bytes",
              name: "operatorNotificationData",
              type: "bytes",
            },
          ],
          name: "OperatorRevoked",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "previousOwner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "OwnershipTransferred",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "tokenId",
              type: "bytes32",
            },
            {
              indexed: true,
              internalType: "bytes32",
              name: "dataKey",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "bytes",
              name: "dataValue",
              type: "bytes",
            },
          ],
          name: "TokenIdDataChanged",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "address",
              name: "operator",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              indexed: true,
              internalType: "bytes32",
              name: "tokenId",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "force",
              type: "bool",
            },
            {
              indexed: false,
              internalType: "bytes",
              name: "data",
              type: "bytes",
            },
          ],
          name: "Transfer",
          type: "event",
        },
        {
          stateMutability: "payable",
          type: "fallback",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "operator",
              type: "address",
            },
            {
              internalType: "bytes32",
              name: "tokenId",
              type: "bytes32",
            },
            {
              internalType: "bytes",
              name: "operatorNotificationData",
              type: "bytes",
            },
          ],
          name: "authorizeOperator",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "tokenOwner",
              type: "address",
            },
          ],
          name: "balanceOf",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes[]",
              name: "data",
              type: "bytes[]",
            },
          ],
          name: "batchCalls",
          outputs: [
            {
              internalType: "bytes[]",
              name: "results",
              type: "bytes[]",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "tokenId",
              type: "bytes32",
            },
          ],
          name: "burn",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "key",
              type: "bytes32",
            },
          ],
          name: "getData",
          outputs: [
            {
              internalType: "bytes",
              name: "",
              type: "bytes",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32[]",
              name: "keys",
              type: "bytes32[]",
            },
          ],
          name: "getDataBatch",
          outputs: [
            {
              internalType: "bytes[]",
              name: "",
              type: "bytes[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32[]",
              name: "tokenIds",
              type: "bytes32[]",
            },
            {
              internalType: "bytes32[]",
              name: "dataKeys",
              type: "bytes32[]",
            },
          ],
          name: "getDataBatchForTokenIds",
          outputs: [
            {
              internalType: "bytes[]",
              name: "dataValues",
              type: "bytes[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "tokenId",
              type: "bytes32",
            },
            {
              internalType: "bytes32",
              name: "dataKey",
              type: "bytes32",
            },
          ],
          name: "getDataForTokenId",
          outputs: [
            {
              internalType: "bytes",
              name: "dataValue",
              type: "bytes",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "tokenId",
              type: "bytes32",
            },
          ],
          name: "getOperatorsOf",
          outputs: [
            {
              internalType: "address[]",
              name: "",
              type: "address[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "operator",
              type: "address",
            },
            {
              internalType: "bytes32",
              name: "tokenId",
              type: "bytes32",
            },
          ],
          name: "isOperatorFor",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              internalType: "string",
              name: "tokenURI_",
              type: "string",
            },
          ],
          name: "mintItem",
          outputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "renounceOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "operator",
              type: "address",
            },
            {
              internalType: "bytes32",
              name: "tokenId",
              type: "bytes32",
            },
            {
              internalType: "bool",
              name: "notify",
              type: "bool",
            },
            {
              internalType: "bytes",
              name: "operatorNotificationData",
              type: "bytes",
            },
          ],
          name: "revokeOperator",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "key",
              type: "bytes32",
            },
            {
              internalType: "bytes",
              name: "value",
              type: "bytes",
            },
          ],
          name: "setData",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32[]",
              name: "keys",
              type: "bytes32[]",
            },
            {
              internalType: "bytes[]",
              name: "values",
              type: "bytes[]",
            },
          ],
          name: "setDataBatch",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32[]",
              name: "tokenIds",
              type: "bytes32[]",
            },
            {
              internalType: "bytes32[]",
              name: "dataKeys",
              type: "bytes32[]",
            },
            {
              internalType: "bytes[]",
              name: "dataValues",
              type: "bytes[]",
            },
          ],
          name: "setDataBatchForTokenIds",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "tokenId",
              type: "bytes32",
            },
            {
              internalType: "bytes32",
              name: "dataKey",
              type: "bytes32",
            },
            {
              internalType: "bytes",
              name: "dataValue",
              type: "bytes",
            },
          ],
          name: "setDataForTokenId",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "tokenId",
              type: "bytes32",
            },
            {
              internalType: "string",
              name: "newTokenURI",
              type: "string",
            },
          ],
          name: "setTokenURI",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes4",
              name: "interfaceId",
              type: "bytes4",
            },
          ],
          name: "supportsInterface",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "tokenOwner",
              type: "address",
            },
          ],
          name: "tokenIdsOf",
          outputs: [
            {
              internalType: "bytes32[]",
              name: "",
              type: "bytes32[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "tokenId",
              type: "bytes32",
            },
          ],
          name: "tokenOwnerOf",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "tokenId",
              type: "bytes32",
            },
          ],
          name: "tokenURI",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "totalSupply",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              internalType: "bytes32",
              name: "tokenId",
              type: "bytes32",
            },
            {
              internalType: "bool",
              name: "force",
              type: "bool",
            },
            {
              internalType: "bytes",
              name: "data",
              type: "bytes",
            },
          ],
          name: "transfer",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address[]",
              name: "from",
              type: "address[]",
            },
            {
              internalType: "address[]",
              name: "to",
              type: "address[]",
            },
            {
              internalType: "bytes32[]",
              name: "tokenId",
              type: "bytes32[]",
            },
            {
              internalType: "bool[]",
              name: "force",
              type: "bool[]",
            },
            {
              internalType: "bytes[]",
              name: "data",
              type: "bytes[]",
            },
          ],
          name: "transferBatch",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "transferOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          stateMutability: "payable",
          type: "receive",
        },
      ],
      inheritedFunctions: {},
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
